[general]

[terminal]

[terminal.shell]
program = "/usr/bin/fish"

[env]

[window]
padding = { x = 10, y = 10}
opacity = 0.1
blur = true
title = "Alacritty"
dynamic_title = false

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }
size = 12

[colors]
transparent_background_colors = true

[colors.primary]
foreground = "#181818"
background = "#f3f3f3"
